### ISSUE TITLE
Dalek reports: "<unknown> is deprecated" issues

### ISSUE THREAD

**Issue by Ben3eeE** [atom/dalek#10]
To reproduce:

1. Run `apm install tree-view`
1. Start Atom
1. Check the deprecation message. Dalek reports that `tree-view` is deprecated and asks to report issue
1. Click to report issue

**Expected:** The title of the issue is `tree-view is deprecated.`
**Actual:** The title of the issue is `<unknown> is deprecated.`

Refs: https://github.com/atom/spell-check/issues/248

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18179
