### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by PixelT** [atom/dalek#4]
You have the core package "dalek" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (C:\Users\username\.atom\packages\dalek\lib\main.js:14:14)
undefined.next (null:null:null)
step (C:\Users\username\.atom\packages\dalek\lib\main.js:1:352)
process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by winstliu** [comment]
You have the core package "dalek" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

**Comment by CodebitsDesign** [comment]
Deprecated calls
dalek (1 deprecation)

<unknown> - /home/bike/.atom/packages/dalek/lib/main.js:14:14
undefined.next - null:null:null
step - /home/bike/.atom/packages/dalek/lib/main.js:1:352
process._tickCallback - internal/process/next_tick.js:103:7
