### ISSUE TITLE
How to leave community package.

### ISSUE THREAD

**Issue by UziTech** [atom/dalek#5]
What if we want the community package instead of the core package?

Some times we want to edit a core package to fit our needs and use the linked package instead of the core package.

**Comment by UziTech** [comment]
or if we want to use the git repo of the core package because it has updated features that are not yet in the core package?

**Comment by UziTech** [comment]
I managed to get around this by changing the `name` in `project.json`

It would be really nice to have an easier way to replace core packages.

Or for that matter not have any core packages.

Why can't core packages just be community packages written by atom and installed by default on new installs?

**Comment by winstliu** [comment]
In both cases you should really be linking the package through `apm link` or `apm dev`.  Dalek explicitly ignores symlinked packages.

**Comment by UziTech** [comment]
That won't work for git packages that you want to auto update with new commits

**Comment by winstliu** [comment]
I don't think we're going to support git versions of core packages.  That's exactly what we're trying to avoid in this case.

**Comment by UziTech** [comment]
Why are you trying to avoid it?

**Comment by winstliu** [comment]
Because most people will leave them installed, even after the features are available in the core package.  This then leads to bugs such as https://github.com/atom/tree-view/issues/1065 or https://github.com/atom/tree-view/issues/1064.

**Comment by UziTech** [comment]
I don't see why that would be a reason not to let anyone use the latest core packages. That would be like saying we aren't going to allow non-core packages because people might think there are errors with core packages.

**Comment by winstliu** [comment]
We do not allow manually installing core packages because they are meant to be paired with specific Atom versions and will occasionally utilize APIs that are not present in older Atom versions: see the tree-view examples listed above.  The versions that are bundled with Atom are tested on that Atom version.  Newer versions may be incompatible.

I'm afraid I don't understand your analogy.

**Comment by UziTech** [comment]
All of the core packages should be tested against the latest stable and beta release so keeping the core package as a git package would be the same thing as using a canary version a software. 

I think warning someone that there could be some issues when installing a core package as a git package would be better than not letting anyone use the latest core package.

**Comment by winstliu** [comment]
Perhaps I should clarify: when I said "do not allow", I really meant "strongly discourage".  That's why you're not forced to uninstall any core packages you have manually installed, and instead pointed to this repository's README.

So 

> I think warning someone that there could be some issues when installing a core package as a git package would be better than not letting anyone use the latest core package.

is exactly what we're doing currently.

> All of the core packages should be tested against the latest stable and beta release so keeping the core package as a git package would be the same thing as using a canary version a software.

I do not believe we are interested in offering or supporting a canary version of Atom, either officially or unofficially by installing core packages as git packages.  We have enough release permutations to take care of as-is.

**Comment by UziTech** [comment]
When I tried having the latest `language-php` package installed as a git package it wouldn't let me enable it. 

It listed a deprecation pointing to this package and disabled the package.

**Comment by UziTech** [comment]
I'm not saying atom should have a canary version just that if someone wants to install the latest core packages from their git repo they should already know that it is like installing a canary version of atom and there might be issues

**Comment by winstliu** [comment]
The key difference here is that what you are describing is **not** a Canary experience, but rather a "mismatched components" experience.  Using Chrome Canary as an example, you download a prebuilt version that is meant to be used as a developmental version, with a considerable warning visible before doing so.
Downloading the latest version of tree-view (with no warning), and then _mismatching it with an Atom version that it was never intended to work with_, is not canary!

**Comment by UziTech** [comment]
Isn't that what the [`engines`](https://docs.npmjs.com/files/package.json#engines) property in package.json is for?

If the core package needs a minimum version of Atom it should specify it in that property and Atom should then alert the user that that version of the package will not work with their version of Atom.

I'm not understanding what the difference is between core packages and community packages other than core packages are written by the Atom team and come automatically installed with atom.
