### ISSUE TITLE
No warning after installing core package as community package

### ISSUE THREAD

**Issue by rsese** [atom/dalek#8]
### Description

While @Ben3eeE was walking me through testing PRs on core packages, we found that the Dalek package wasn't warning us after installing a core package as a community package and then starting Atom.

### Steps to reproduce

1. Install a core package with `apm` e.g. `apm install find-and-replace`.
2. Start Atom

For example:

```
$ apm install find-and-replace
The find-and-replace package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall find-and-replace` to uninstall it and then the version bundled
with Atom will be used.
```

Then started Atom and see no warning though we can see:

![installed-core-package](https://github-slack.s3.amazonaws.com/monosnap/Settings__workjs-excercises_2017-09-11_15-58-56.png)

**Expected behavior:** 

Expect to get warning about the core package installed as a community package.

**Actual behavior:** [What actually happens]

Actual behavior is that there's no warning after starting Atom.

### Versions

```
atom -v
Atom    : 1.22.0-dev-841104a73
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

macOS 10.12.6

### Additional Information

@Ben3eeE dug into things more :mag: and mentioned:

> it regressed in Atom 1.17. Probably from snapshot changes. The dalek package uses `atom.packages.getAvailablePackagePaths()`to find duplicate packages and that no longer returns both packages. It only returns the `find-and-replace`I installed manually. It seems that this function changed with snapshots in https://github.com/atom/atom/commit/b913ad8bb584a3ec370da15b5e8ec6ffb6dd00a0

**Comment by iolsen** [comment]
@lee-dohm can you look at this one?
